name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Python version
        run: python3.11 --version

      - name: Install dependencies
        run: |
          python3.11 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install flake8 pytest || true

      - name: Run lint and tests (non-blocking)
        run: |
          source venv/bin/activate
          flake8 . || true
          pytest || true
        if: always()

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi_demo:latest

  deploy-to-vm:
    # если есть self-hosted runner → деплой локально
    runs-on: ${{ github.runner == 'self-hosted' && 'self-hosted' || 'ubuntu-latest' }}
    needs: docker-build-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy (self-hosted)
        if: runner.environment == 'self-hosted'
        env:
          IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi_demo:latest
        run: |
          docker pull ${IMAGE}
          docker stop fastapi_demo || true
          docker rm fastapi_demo || true
          docker run -d --name fastapi_demo -p 8081:8000 ${IMAGE}

      - name: Setup SSH (cloud runner)
        if: runner.environment != 'self-hosted'
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Add VM to known hosts (cloud runner)
        if: runner.environment != 'self-hosted'
        run: ssh-keyscan -H ${{ secrets.DEPLOY_VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH (cloud runner)
        if: runner.environment != 'self-hosted'
        env:
          SSH_USER: ${{ secrets.DEPLOY_VM_USER }}
          SSH_HOST: ${{ secrets.DEPLOY_VM_HOST }}
          IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi_demo:latest
        run: |
          ssh "${SSH_USER}@${SSH_HOST}" << 'EOF'
          set -e
          docker pull ${IMAGE}
          docker stop fastapi_demo || true
          docker rm fastapi_demo || true
          docker run -d --name fastapi_demo -p 8081:8000 ${IMAGE}
          EOF

